/**
 * HR_USER
 */
CREATE TABLE HR_USER 
(
	USERID            BIGINT NOT NULL,
	NAME              VARCHAR (2000),
	EMPNO             VARCHAR (32),
	DPRT_NAME         VARCHAR (1000),
	JOB_TITLE         VARCHAR (32),
	LOGIN_ID          VARCHAR (32),
	LOGIN_PSWD        VARCHAR (64),
	E_MAIL            VARCHAR (128),
	FRST_INST         DATETIME DEFAULT CURRENT_TIMESTAMP,
	LAST_UPDT         DATETIME DEFAULT CURRENT_TIMESTAMP,
	ISVISB            INT DEFAULT 0 NOT NULL,
	STATUS            INT DEFAULT 0,
	ISADMIN           INT DEFAULT 0,
	HIRE_DATE         DATETIME,
	RETR_DATE         DATETIME,
	OFCE_PHN          VARCHAR (32),
	OFCE_FAX          VARCHAR (32),
	OFCE_ADRS         VARCHAR (255),
	MBL_PHN           VARCHAR (32),
	HOME_PHN          VARCHAR (32),
	PICT_SAVE_CODE    INT DEFAULT -1,
	PICT_SAVE_PATH    VARCHAR (500),
	THUMB_SAVE_CODE   INT DEFAULT -1,
	THUMB_SAVE_PATH   VARCHAR (500),
	CONDITION_TEXT    VARCHAR (500)
);
ALTER TABLE HR_USER ADD
CONSTRAINT XPK_HR_USER PRIMARY KEY (USERID);

ALTER TABLE HR_USER MODIFY USERID BIGINT AUTO_INCREMENT;

/**
 * BLOG_ITEM
 */
CREATE TABLE BLOG_ITEM
(
	ITEMID		BIGINT(8) NOT NULL COMMENT '블로그일련번호',
	USERID      BIGINT NOT NULL	COMMENT '사용자일련번호',
	NAME        VARCHAR (2000) COMMENT '사용자이름',
	TITLE		VARCHAR (1000) NOT NULL COMMENT '블로그제목',
	TYPE		VARCHAR (100) NOT NULL COMMENT '블로그타입',
	COMMENT		VARCHAR (4000) COMMENT '블로그설명',
	RGST_DATE	DATETIME DEFAULT NOW() NOT NULL COMMENT '생성일자',
	LAST_DATE	DATETIME DEFAULT NOW() NOT NULL COMMENT '수정일자'
) COMMENT = '블로그';
ALTER TABLE BLOG_ITEM ADD 
CONSTRAINT XPK_BLOG_ITEM PRIMARY KEY (ITEMID);

ALTER TABLE BLOG_ITEM MODIFY ITEMID BIGINT(8) AUTO_INCREMENT;

ALTER TABLE BLOG_ITEM ADD (
  CONSTRAINT XFK_BLOG_ITEM_USERID FOREIGN KEY (USERID)
  REFERENCES HR_USER(USERID)
);

/**
 * BBS_ITEM
 */
CREATE TABLE BBS_ITEM
(
	ITEMID                 BIGINT(8) NOT NULL,
	TITLE                  VARCHAR(1000) NOT NULL,
	CONTENT                LONGTEXT,
	USERID                 BIGINT(8) NOT NULL,
	USER_NAME              VARCHAR(500),
	RGST_DATE              DATETIME DEFAULT NOW() NOT NULL,
	LAST_DATE              DATETIME DEFAULT NOW() NOT NULL,
	FILE_CNT               BIGINT(8) DEFAULT 0 NOT NULL,    
	FILE_EXT               VARCHAR(100),    
	DEL_YN                 VARCHAR(1) DEFAULT 'N' NOT NULL,
	NOTICE                 VARCHAR(1) DEFAULT 'N' NOT NULL,
	SCRT_TYPE			         VARCHAR(100),
	NTCE_STRT_DATE		     DATETIME,
	NTCE_LAST_DATE		     DATETIME
);
ALTER TABLE BBS_ITEM ADD 
CONSTRAINT XPK_BBS_ITEM PRIMARY KEY (ITEMID);

ALTER TABLE BBS_ITEM MODIFY ITEMID BIGINT(8) AUTO_INCREMENT;

ALTER TABLE BBS_ITEM ADD (
  CONSTRAINT XFK_BBS_ITEM_USERID FOREIGN KEY (USERID)
  REFERENCES HR_USER(USERID)
);