/**
 * BLOG_ITEM
 */
COMMENT ON TABLE BLOG_ITEM IS '블로그'; 
COMMENT ON COLUMN BLOG_ITEM.ITEMID IS '블로그일련번호';
COMMENT ON COLUMN BLOG_ITEM.USERID IS '사용자일련번호';
COMMENT ON COLUMN BLOG_ITEM.NAME IS '사용자이름';
COMMENT ON COLUMN BLOG_ITEM.TITLE IS '블로그제목';
COMMENT ON COLUMN BLOG_ITEM.TYPE IS '블로그타입';
COMMENT ON COLUMN BLOG_ITEM.COMMENT IS '블로그설명';
COMMENT ON COLUMN BLOG_ITEM.RGST_DATE IS '생성일자';
COMMENT ON COLUMN BLOG_ITEM.LAST_DATE IS '수정일자';